version: '3.8'

services:
  web:
    build: .
    image: dock-hosting-app:custom-fix
    container_name: dock-hosting-app
    restart: always
    volumes:
      - .:/var/www/html
      - /home/deployer/dock-hosting-data:/var/www/html/users
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - proxy_network
      - default
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=dock_hosting
      - HOST_BASE_PATH=${HOST_BASE_PATH:-/home/deployer/dock-hosting-data}
      - VIRTUAL_HOST=dockhosting.dev,www.dockhosting.dev
      - LETSENCRYPT_HOST=dockhosting.dev,www.dockhosting.dev
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-admin@dockhosting.dev}

  db:
    image: mysql:8.0
    container_name: dock-hosting-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: dock_hosting
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default
      - proxy_network

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: dock-hosting-pma
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=100M
      - VIRTUAL_HOST=pma.dockhosting.dev
      - LETSENCRYPT_HOST=pma.dockhosting.dev
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-admin@dockhosting.dev}
    networks:
      - default
      - proxy_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  proxy_network:
    external: true
