version: '3.8'

services:
  web:
    build: .
    container_name: dock-hosting-app
    restart: always
    volumes:
      - .:/var/www/html
      - ${STORAGE_PATH:-./users}:/var/www/html/users
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - proxy_network
      - default
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=dock_hosting
      - HOST_BASE_PATH=${HOST_BASE_PATH:-/var/www/html/users}
      - VIRTUAL_HOST=dockhosting.dev,www.dockhosting.dev
      - LETSENCRYPT_HOST=dockhosting.dev,www.dockhosting.dev
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-admin@dockhosting.dev}

  db:
    image: mysql:8.0
    container_name: dock-hosting-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: dock_hosting
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

volumes:
  db_data:

networks:
  proxy_network:
    external: true
